---
- name: Install certbot and certbot Nginx plugin
  ansible.builtin.apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: yes
  tags: certbot
  become: true

- name: Generate certificate using certbot for Nginx
  ansible.builtin.command:
    cmd: certbot --nginx -d {{ nginx_server_name }} --non-interactive --agree-tos --email {{ certbot_email }}
    creates: /etc/letsencrypt/live/{{ nginx_server_name }}/fullchain.pem
  notify: Reload nginx
  tags: certbot
  become: true
