---
galaxy_info:
  author: korkin25
  description: Install systemd controlled software from standard APT repositories
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  license: BSD
  min_ansible_version: 2.14
dependencies: []
