---
galaxy_info:
  author: korkin25
  description: Letsencrypt installation for spefied domain
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  license: BSD
  min_ansible_version: "2.14"
dependencies: []
