---
all:
  hosts:
    somehost1.info:
      nginx_url_secret: "top_secret"
      nginx_server_name: "some.site.info"
      nginx_listen_port: "80"
      certbot_email: "root@cdrom.com"

  vars:
    common_packages:
      - wajig
      - aptitude
      - vim-nox
    open_ports:
      - 80/tcp
      - 443/tcp
      - 65222/tcp
      - 22/tcp
  children:
    webhosts:
      hosts:
        somehost1.info:
          host_packages:
            - mc
            - wajig
      vars:
        services:
          nginx:
            package: "nginx-extras"
            unit_name: "nginx"
            enabled: true
            log_file: "/var/log/nginx/error.log"
            configs:
              secure-link:
                src: "files/nginx/secure-link.conf.j2"
                dest: "/etc/nginx/sites-enabled/secure-link.conf"
                mode: "0644"
                owner: root
                group: root
                enabled: true
              nginx_conf:
                src: "files/nginx/nginx.conf.j2"
                dest: "/etc/nginx/nginx.conf"
                mode: "0644"
                owner: root
                group: root
                enabled: true
          fail2ban:
            package: "fail2ban"
            unit_name: "fail2ban"
            log_file: "/var/log/fail2ban.log"
            enabled: true
            configs:
              jail:
                src: "files/fail2ban/jail.local"
                dest: "/etc/fail2ban/jail.local"
                mode: "0644"
                owner: root
                group: root
