---
all:
  hosts:
    kk573-hp:
  vars:
    common_packages:
      - wajig
      - aptitude
      - vim-nox
  children:
    default_skel:
      hosts:
        kk573-hp:
          host_packages:
            - mc
            - wajig
