---
all:
  hosts:
    testhost:
  vars:
    common_packages:
      - wajig
      - aptitude
      - vim-nox
    open_ports:
      - 80/tcp
      - 443/tcp
      - 65222/tcp
      - 22/tcp
  children:
    default_skel:
      hosts:
        testhost:
          host_packages:
            - mc
            - wajig
