#vim: set ft=yaml.ansible
---

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags: packages

- name: Concatenate variables
  ansible.builtin.set_fact:
    all_packages: "{{ (common_packages + host_packages) | unique | sort }}"
  tags: packages

- name: "Install packages: {{ all_packages | join(', ') }}"
  ansible.builtin.apt:
    name: "{{ all_packages }}"
    state: present
  become: yes
  tags: packages
