---

- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: latest
  become: true
  tags: ufw

- name: Set default UFW policies
  community.general.ufw:
    direction: incoming
    policy: deny
  become: true
  tags: ufw

- name: Retrieve UFW rules
  ansible.builtin.command:
    cmd: ufw status numbered
  register: raw_ufw_status
  changed_when: false
  become: true
  tags: ufw

- name: Extract current UFW rules into a list
  ansible.builtin.set_fact:
    ufw_current_rule_list: "{{ raw_ufw_status.stdout_lines | regex_findall('\\[\\s?\\d+\\]\\s+(\\S+/(?:tcp|udp))') }}"
  tags: ufw

- name: Debug UFW rules
  ansible.builtin.debug:
    msg: "{{ ufw_current_rule_list }}"
  tags: ufw

- name: Allow incoming connections on specific ports {{ open_ports }}}
  community.general.ufw:
    rule: allow
    port: "{{ item.split('/')[0] }}"
    proto: "{{ item.split('/')[1] }}"
  loop: "{{ open_ports }}"
  become: true
  tags: ufw

- name: Identify rules to be removed
  ansible.builtin.set_fact:
    rules_to_remove: "{{ ufw_current_rule_list | difference(open_ports) }}"
  tags: ufw

- name: Remove UFW rules not in open_ports {{ rules_to_remove }}}
  ansible.builtin.command:
    cmd: "ufw delete allow {{ item.split('/')[0] }}/{{ item.split('/')[1] }}"
  loop: "{{ rules_to_remove }}"
  become: true
  when: rules_to_remove | length > 0
  tags: ufw

- name: Enable UFW
  community.general.ufw:
    state: enabled
  become: true
  tags: ufw
