name: Ansible Lint

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Ansible Lint Action
        uses: korkin25/actions/ansible-lint@main
        with:
          playbook: main.yaml
